#!/usr/bin/env bash
# tools/cleanup.sh — Teardown and handoff script for pkcs11-fuzzer.
#
# Designed for the moment when a fuzzing session ends and the user is done.
# Runs in three independent, opt-in tiers so you keep exactly what you need.
#
# Tiers (each is independent; combine freely):
#   --artifacts   Runtime output: crashes, corpus, coverage,
#                 compiled harness binaries, token snapshot.
#                 Safe to delete — fully regenerated by build-all.sh + make.
#
#   --targets     Sanitized target builds: builds/{libfuzzer,tsan}/
#                 and per-tree build dirs in src/.  Frees the most space
#                 after --sources (several GB).  Rebuild with build-all.sh.
#
#   --sources     All cloned source trees (src/).  Combined with --targets
#                 this is a full teardown of everything that can be
#                 regenerated.
#
# Convenience combinations:
#   --all         Equivalent to --artifacts --targets --sources
#   --soft        Equivalent to --artifacts only (keeps built targets)
#   --hard        Equivalent to --artifacts --targets (keeps source clones)
#
# Usage:
#   bash tools/cleanup.sh                       # interactive menu
#   bash tools/cleanup.sh --soft                # delete runtime output only
#   bash tools/cleanup.sh --hard                # delete output + target builds
#   bash tools/cleanup.sh --all                 # full teardown
#   bash tools/cleanup.sh --dry-run --all       # show what would be deleted
#   bash tools/cleanup.sh --archive /mnt/share  # archive findings first
#   bash tools/cleanup.sh --summary             # print session summary + exit
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PYTHON="$(command -v python3)"

cd "$PROJECT_ROOT"

# ---------------------------------------------------------------------------
# Flags
# ---------------------------------------------------------------------------
DO_ARTIFACTS=0
DO_TARGETS=0
DO_SOURCES=0
DRY_RUN=0
ARCHIVE_DIR=""
SUMMARY_ONLY=0
INTERACTIVE=1    # set to 0 when any explicit flag is given

for arg in "$@"; do
    case "$arg" in
        --artifacts)  DO_ARTIFACTS=1; INTERACTIVE=0 ;;
        --targets)    DO_TARGETS=1;   INTERACTIVE=0 ;;
        --sources)    DO_SOURCES=1;   INTERACTIVE=0 ;;
        --soft)       DO_ARTIFACTS=1; INTERACTIVE=0 ;;
        --hard)       DO_ARTIFACTS=1; DO_TARGETS=1; INTERACTIVE=0 ;;
        --all)        DO_ARTIFACTS=1; DO_TARGETS=1; DO_SOURCES=1; INTERACTIVE=0 ;;
        --dry-run)    DRY_RUN=1 ;;
        --summary)    SUMMARY_ONLY=1 ;;
        --archive=*)  ARCHIVE_DIR="${arg#--archive=}"; INTERACTIVE=0 ;;
        --archive)    ;;   # next arg handled below
        *)
            # Handle --archive <dir> as two separate args
            if [[ "${PREV_ARG:-}" == "--archive" ]]; then
                ARCHIVE_DIR="$arg"
            fi
            ;;
    esac
    PREV_ARG="$arg"
done

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
hr() { printf '─%.0s' {1..64}; echo; }

disk_size() {
    local path="$1"
    [[ -e "$path" ]] || { echo "0 B"; return; }
    du -sh "$path" 2>/dev/null | cut -f1
}

rm_dir() {
    local path="$1" label="$2"
    if [[ ! -e "$path" ]]; then
        echo "  [skip] $label (not present)"
        return
    fi
    local size
    size=$(disk_size "$path")
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "  [dry-run] would remove $label  ($size)"
    else
        echo "  removing $label  ($size) …"
        rm -rf "$path"
        echo "  done."
    fi
}

confirm() {
    local msg="$1" default="${2:-y}"
    [[ $DRY_RUN -eq 1 ]] && return 0
    local prompt="[Y/n]"
    [[ "$default" == "n" ]] && prompt="[y/N]"
    printf "\n  %s %s: " "$msg" "$prompt"
    read -r ans
    [[ -z "$ans" ]] && ans="$default"
    [[ "${ans,,}" == "y" ]]
}

# ---------------------------------------------------------------------------
# Step 0: Always print summary first
# ---------------------------------------------------------------------------
echo ""
hr
echo "  pkcs11-fuzzer — Session Wrap-up"
hr
"$PYTHON" "$SCRIPT_DIR/summarize.py" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Step 1: Archive findings (optional)
# Archive is processed BEFORE the summary-only exit so that
# --summary --archive=DIR can be used to save findings without cleaning.
# ---------------------------------------------------------------------------
do_archive() {
    local dest="$1"
    mkdir -p "$dest"
    echo ""
    echo "  Archiving findings → $dest"

    # Crash reports and patches
    if [[ -d crashes/analysis ]]; then
        cp -r crashes/analysis "$dest/"
        echo "    crashes/analysis/ → $dest/analysis/"
    fi

    # Deduplicated crash inputs
    if [[ -d crashes/deduplicated ]]; then
        cp -r crashes/deduplicated "$dest/"
        echo "    crashes/deduplicated/ → $dest/deduplicated/"
    fi

    # Findings summary JSON
    if [[ -f crashes/findings_summary.json ]]; then
        cp crashes/findings_summary.json "$dest/"
        echo "    findings_summary.json → $dest/"
    fi

    # Notification log
    if [[ -f coverage/notifications.log ]]; then
        cp coverage/notifications.log "$dest/"
        echo "    notifications.log → $dest/"
    fi

    # Write a README for the archive
    cat > "$dest/ARCHIVE_README.md" <<EOF
# pkcs11-fuzzer Findings Archive

Generated: $(date -u '+%Y-%m-%d %H:%M UTC')
Machine:   $(hostname)

## Contents

- \`analysis/\`          — Per-crash: report.md, patch.diff, reproducer.bin, workflow_state.json
- \`deduplicated/\`      — Unique crash inputs (one per unique stack key)
- \`findings_summary.json\` — Machine-readable summary of all findings
- \`notifications.log\`  — Timestamped log of all crash notifications

## Reproducing a crash

Each \`analysis/<crash>/reproducer.sh\` is a self-contained shell script.
It writes the minimized crash input and runs the harness binary.
Requires the fuzzer project to be built (\`build-all.sh\` + \`make -C harnesses/\`).

## Applying a patch

\`\`\`bash
cd <pkcs11-fuzzer root>
patch -p1 --dry-run < analysis/<crash>/patch.diff   # check first
patch -p1           < analysis/<crash>/patch.diff   # apply
\`\`\`

Or use the automated workflow:
\`\`\`bash
python3 tools/patch_workflow.py \
    --analysis analysis/<crash> \
    deduplicated/<crash_input>
\`\`\`
EOF

    echo ""
    echo "  Archive complete: $dest"
    echo "  Size: $(disk_size "$dest")"
}

if [[ -n "$ARCHIVE_DIR" ]]; then
    if [[ $DRY_RUN -eq 1 ]]; then
        echo ""
        echo "  [dry-run] would archive findings to: $ARCHIVE_DIR"
    else
        do_archive "$ARCHIVE_DIR"
    fi
fi

# Summary-only: archive (if requested) is done above; now exit
[[ $SUMMARY_ONLY -eq 1 ]] && exit 0

# ---------------------------------------------------------------------------
# Step 2: Interactive menu (when no explicit tier flags given)
# ---------------------------------------------------------------------------
if [[ $INTERACTIVE -eq 1 ]]; then
    echo ""
    hr
    echo "  What would you like to clean up?"
    hr
    echo ""
    echo "  [1] Artifacts only  (crashes, corpus, coverage, harness binaries)"
    echo "      Keeps: sanitized target builds, source clones"
    echo "      Frees: ~$(disk_size crashes) crashes + $(disk_size corpus) corpus + $(disk_size coverage) coverage"
    echo ""
    echo "  [2] Artifacts + target builds  (adds builds/libfuzzer,tsan + src build dirs)"
    echo "      Keeps: source clones"
    echo "      Rebuild time: ~15 min (OpenSSL × 2 + SoftHSM2 × 2 + libp11 × 2 + OpenSC × 2)"
    echo ""
    echo "  [3] Full teardown  (everything that can be regenerated)"
    echo "      Keeps: scripts, harness .c source, README"
    echo "      Rebuild time: ~15 min"
    echo "      Total freeable: ~$(disk_size builds) builds + ~$(disk_size src) src"
    echo ""
    echo "  [4] Summary only  (already shown above — exit without deleting)"
    echo ""
    printf "  Choice [1-4]: "
    read -r choice
    case "$choice" in
        1) DO_ARTIFACTS=1 ;;
        2) DO_ARTIFACTS=1; DO_TARGETS=1 ;;
        3) DO_ARTIFACTS=1; DO_TARGETS=1; DO_SOURCES=1 ;;
        4) echo "  Nothing deleted."; exit 0 ;;
        *) echo "  Invalid choice. Nothing deleted."; exit 1 ;;
    esac

    if [[ -z "$ARCHIVE_DIR" ]]; then
        printf "\n  Archive findings before cleaning? [y/N]: "
        read -r arch_ans
        if [[ "${arch_ans,,}" == "y" ]]; then
            printf "  Archive destination directory: "
            read -r ARCHIVE_DIR
            [[ -n "$ARCHIVE_DIR" ]] && do_archive "$ARCHIVE_DIR"
        fi
    fi

    echo ""
    hr
    echo "  About to delete:"
    [[ $DO_ARTIFACTS -eq 1 ]] && echo "    • Runtime artifacts (crashes, corpus, coverage, harness binaries)"
    [[ $DO_TARGETS   -eq 1 ]] && echo "    • Sanitized target builds (builds/{libfuzzer,tsan}, src/*/build-*)"
    [[ $DO_SOURCES   -eq 1 ]] && echo "    • Source clones (src/)"
    hr
    if ! confirm "Proceed with deletion?"; then
        echo "  Cancelled — nothing deleted."
        exit 0
    fi
fi

# ---------------------------------------------------------------------------
# Step 3: Execute deletions
# ---------------------------------------------------------------------------
echo ""
[[ $DRY_RUN -eq 1 ]] && echo "  DRY RUN — no files will actually be deleted"
echo ""

# ── Tier 1: Artifacts ───────────────────────────────────────────────────────
if [[ $DO_ARTIFACTS -eq 1 ]]; then
    echo "── Artifacts ──────────────────────────────────────────────────"
    rm_dir "crashes/raw"           "crashes/raw/"
    rm_dir "crashes/deduplicated"  "crashes/deduplicated/"
    rm_dir "crashes/analysis"      "crashes/analysis/"

    # Remove evolved corpus entries but keep the directory structure
    if [[ -d corpus ]]; then
        if [[ $DRY_RUN -eq 1 ]]; then
            if [[ $DO_TARGETS -eq 1 || $DO_SOURCES -eq 1 ]]; then
                echo "  [dry-run] would remove corpus/ entirely (full teardown)"
            else
                echo "  [dry-run] would delete all corpus files; empty directories kept"
                echo "             (directories remain so fuzzer can restart immediately)"
            fi
        else
            if [[ $DO_TARGETS -eq 1 || $DO_SOURCES -eq 1 ]]; then
                rm -rf corpus
                echo "  removed corpus/ entirely."
            else
                find corpus -mindepth 2 -type f -delete 2>/dev/null || true
                echo "  deleted all corpus files. Empty directories kept for next run."
                echo "  (run 'make -C harnesses/ seeds' to regenerate seed corpus)"
            fi
        fi
    fi

    rm_dir "coverage"              "coverage/"
    rm_dir "token-template"        "token-template/"

    # Compiled harness binaries (not source)
    if [[ $DRY_RUN -eq 1 ]]; then
        echo "  [dry-run] would remove compiled harness binaries in harnesses/"
    else
        find harnesses/ -maxdepth 1 -type f -executable \
            ! -name "*.c" ! -name "*.h" ! -name "Makefile" \
            -delete 2>/dev/null || true
        echo "  removed compiled harness binaries."
    fi
    echo ""
fi

# ── Tier 2: Target builds ────────────────────────────────────────────────────
if [[ $DO_TARGETS -eq 1 ]]; then
    echo "── Target builds ───────────────────────────────────────────────"
    rm_dir "builds/libfuzzer"      "builds/libfuzzer/"
    rm_dir "builds/tsan"           "builds/tsan/"

    # Per-tree build dirs inside src/
    for comp in openssl softhsm2 libp11 opensc; do
        for tree in libfuzzer tsan; do
            bd="src/$comp/build-$tree"
            rm_dir "$bd" "$bd/"
        done
    done
    echo ""
fi

# ── Tier 3: Sources ──────────────────────────────────────────────────────────
if [[ $DO_SOURCES -eq 1 ]]; then
    echo "── Source clones ───────────────────────────────────────────────"
    rm_dir "src/openssl"       "src/openssl/"
    rm_dir "src/softhsm2"      "src/softhsm2/"
    rm_dir "src/libp11"        "src/libp11/"
    rm_dir "src/opensc"        "src/opensc/"
    # Remove src/ itself if now empty
    if [[ -d src && -z "$(ls -A src 2>/dev/null)" ]]; then
        [[ $DRY_RUN -eq 0 ]] && rmdir src 2>/dev/null || true
    fi
    echo ""
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
hr
if [[ $DRY_RUN -eq 1 ]]; then
    echo "  Dry run complete — no files were deleted."
else
    echo "  Cleanup complete."
    echo ""
    echo "  What remains:"
    echo "    build-scripts/     — all build scripts (re-run build-all.sh to rebuild)"
    echo "    harnesses/*.c *.h  — harness source code"
    echo "    fuzzing/           — fuzzing scripts"
    echo "    tools/             — analysis and cleanup tools"
    echo "    README.md          — documentation"
    [[ $DO_SOURCES -eq 0 && -d src ]] && \
        echo "    src/               — source clones (kept)"
    echo ""
    echo "  To start a fresh fuzzing session on this machine:"
    echo "    bash build-scripts/build-all.sh"
    echo "    make -C harnesses/"
    echo "    screen -dmS fuzz bash fuzzing/continuous.sh"
fi
hr
echo ""
